/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HighlightHelper
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/helpers.ts
var import_obsidian = require("obsidian");
var NOTICE_TIMEOUT = 2400;
async function copyMarks(app, setting) {
  var _a;
  const mdFile = app.workspace.getActiveFile();
  if (!mdFile) {
    new import_obsidian.Notice("Active note not found", NOTICE_TIMEOUT);
    return;
  }
  let content = await app.vault.read(mdFile);
  if (content === null) {
    new import_obsidian.Notice("Cannot read the note content", NOTICE_TIMEOUT);
    return;
  }
  try {
    let marks = [];
    let patterns = setting.patterns.split("\n");
    if (!patterns) {
      new import_obsidian.Notice("Use after setting regular expressions", NOTICE_TIMEOUT);
      return;
    }
    let regex = patterns.map((v) => {
      return "(" + v + ")";
    }).join("|");
    let regExp = new RegExp(regex, "g");
    if (!setting.keep_style) {
      let match = null;
      while (match = regExp.exec(content)) {
        let full = match[0];
        match.reverse().map((v) => {
          if (v && v !== full) {
            marks.push(v);
            return false;
          }
        });
      }
    } else {
      (_a = content.match(new RegExp(regex, "g"))) == null ? void 0 : _a.map(function(marked) {
        marks.push(marked);
        return marked;
      });
    }
    if (marks.length == 0) {
      new import_obsidian.Notice("Highlight not found!!", NOTICE_TIMEOUT);
      return;
    }
    if (setting.as_list) {
      marks = marks.map(function(marked) {
        return "- " + marked;
      });
    }
    let copy = marks.join("\n");
    if (setting.header_text) {
      copy = setting.header_text + "\n" + copy;
    }
    navigator.clipboard.writeText(copy);
    new import_obsidian.Notice("All highlights are copied!!", NOTICE_TIMEOUT);
  } catch (e) {
    console.error(e);
  }
}

// src/settings.ts
var import_obsidian2 = require("obsidian");
var HHSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Regex patterns").setDesc(
      `regular expressions to extract marks (one expressen per line).`
    ).addTextArea((text) => {
      text.setValue(this.plugin.settings.patterns).onChange(async (value) => {
        this.plugin.settings.patterns = value;
        await this.plugin.saveSettings();
      }).then((text2) => {
        text2.inputEl.className = "regex-patterns";
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Header text").setDesc(
      "If set header text, it will be attached on the top of the copied highlights"
    ).addText(
      (text) => text.setValue(this.plugin.settings.header_text).onChange(async (value) => {
        this.plugin.settings.header_text = value;
        await this.plugin.saveSettings();
      }).then((text2) => {
        text2.inputEl.className = "header-text";
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Copy as list").setDesc("If enabled, highlights will be copied as a list").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.as_list).onChange((value) => {
        this.plugin.settings.as_list = value;
        this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Copy with highlight style").setDesc(
      "If enabled, highlights will be copied with highlight code. (e.g. == HIGHLIGHT TEXT ==) If disabled, only highlighted texts will be copied (e.g. HIGHLIGHT TEXT)"
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.keep_style).onChange((value) => {
        this.plugin.settings.keep_style = value;
        this.plugin.saveSettings();
      });
    });
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  patterns: "<mark(.*?)>(.*?)</mark>\n==(.*?)==",
  header_text: "",
  as_list: false,
  keep_style: false
};
var HighlightHelper = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.longTapTimeoutId = null;
  }
  async onload() {
    await this.loadSettings();
    const ribbonIconEl = this.addRibbonIcon(
      "clipboard-list",
      "Copy Marks",
      (evt) => {
        copyMarks(this.app, this.settings);
      }
    );
    ribbonIconEl.addClass("hh-btn-copy");
    this.addCommand({
      id: "copy-command",
      name: "Copy Marks",
      callback: () => {
        copyMarks(this.app, this.settings);
      }
    });
    this.addSettingTab(new HHSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onElement(el, event, selector, listener, options) {
    el.on(event, selector, listener, options);
    return () => el.off(event, selector, listener, options);
  }
};
