/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WallabagPlugin
});
module.exports = __toCommonJS(main_exports);

// src/command/DeleteNoteAndRemoveFromSyncedCacheCommand.ts
var import_obsidian = require("obsidian");
var DeleteNoteAndRemoveFromSyncedCacheCommand = class {
  constructor(plugin) {
    this.id = "delete-and-remove-from-synced-articles-cache";
    this.name = "Delete note and remove it from synced articles cache";
    this.plugin = plugin;
    this.syncedFilePath = `${this.plugin.manifest.dir}/.synced`;
  }
  async callback() {
    const notice = new import_obsidian.Notice("Delete note and remove it from synced articles cache.");
    const currentNote = this.plugin.app.workspace.getActiveFile();
    if (currentNote instanceof import_obsidian.TFile) {
      const cmeta = this.plugin.app.metadataCache.getFileCache(currentNote);
      let wallabag_id = (0, import_obsidian.parseFrontMatterEntry)(cmeta?.frontmatter, "wallabag_id");
      if (wallabag_id === null) {
        new import_obsidian.Notice("Error: Wallabag ID not found in frontmatter. Please see plugin docs.");
        notice.hide();
        return;
      }
      wallabag_id = Number(wallabag_id);
      if (isNaN(wallabag_id) || wallabag_id === 0) {
        new import_obsidian.Notice("Error: Wallabag ID frontmatter doesn't seem to be a valid number.");
        notice.hide();
        return;
      }
      const exists = await this.plugin.app.vault.adapter.exists(this.syncedFilePath);
      if (exists) {
        const syncedIds = await this.plugin.app.vault.adapter.read(this.syncedFilePath).then(JSON.parse);
        syncedIds.forEach((item, index) => {
          if (item === wallabag_id) {
            syncedIds.splice(index, 1);
          }
        });
        await this.plugin.app.vault.adapter.write(this.syncedFilePath, JSON.stringify(syncedIds));
      }
      await this.plugin.app.vault.trash(currentNote, false);
      new import_obsidian.Notice("Note is moved to trash and removed from synced articles cache.");
    } else {
      new import_obsidian.Notice("Error: Current item is not a note.");
    }
    notice.hide();
  }
};

// src/command/ResetSyncedArticlesCacheCommand.ts
var import_obsidian2 = require("obsidian");
var ClearSyncedArticlesCacheCommand = class {
  constructor(plugin) {
    this.id = "clear-synced-articles-cache";
    this.name = "Clear synced articles cache";
    this.plugin = plugin;
    this.syncedFilePath = `${this.plugin.manifest.dir}/.synced`;
  }
  async callback() {
    const notice = new import_obsidian2.Notice("Clearing synced articles cache.");
    await this.plugin.app.vault.adapter.write(this.syncedFilePath, JSON.stringify([]));
    notice.hide();
    new import_obsidian2.Notice("Synced articles cache is cleared.");
  }
};

// src/note/NoteTemplate.ts
var import_obsidian3 = require("obsidian");
var NoteTemplate = class {
  constructor(content) {
    this.content = content;
  }
  fill(wallabagArticle, serverBaseUrl, convertHtmlToMarkdown, tagFormat, pdfLink = "") {
    const content = wallabagArticle.content !== null ? wallabagArticle.content : "";
    const annotations = wallabagArticle.annotations.map((a) => "> " + a.quote + (a.text ? "\n\n" + a.text : "")).join("\n\n");
    const variables = {
      "{{id}}": wallabagArticle.id.toString(),
      "{{article_title}}": wallabagArticle.title,
      "{{original_link}}": wallabagArticle.url,
      "{{given_url}}": wallabagArticle.givenUrl,
      "{{created_at}}": wallabagArticle.createdAt,
      "{{published_at}}": wallabagArticle.publishedAt,
      "{{updated_at}}": wallabagArticle.updatedAt,
      "{{wallabag_link}}": `${serverBaseUrl}/view/${wallabagArticle.id}`,
      "{{content}}": convertHtmlToMarkdown === "true" ? (0, import_obsidian3.htmlToMarkdown)(content) : content,
      "{{pdf_link}}": pdfLink,
      "{{tags}}": this.formatTags(wallabagArticle.tags, tagFormat),
      "{{reading_time}}": wallabagArticle.readingTime,
      "{{preview_picture}}": wallabagArticle.previewPicture,
      "{{domain_name}}": wallabagArticle.domainName,
      "{{annotations}}": annotations,
      "{{is_archived}}": wallabagArticle.isArchived ? "true" : "false",
      "{{is_starred}}": wallabagArticle.isStarred ? "true" : "false"
    };
    let noteContent = this.content;
    Object.keys(variables).forEach((key) => {
      noteContent = noteContent.replaceAll(key, variables[key]);
    });
    return noteContent;
  }
  formatTags(tags, tagFormat) {
    switch (tagFormat) {
      case "csv":
        return tags.join(", ");
      case "hashtag":
        return tags.map((tag) => `#${tag}`).join(" ");
      default:
        return "";
    }
  }
};
var DefaultTemplate = new NoteTemplate(
  "---\ntags: {{tags}}\n---\n ## {{article_title}} []({{original_link}})[]({{wallabag_link}})\n{{content}}"
);
var PDFTemplate = new NoteTemplate(
  "---\ntags: {{tags}}\n---\n ## {{article_title}} []({{original_link}})[]({{wallabag_link}})\nPDF: [[{{pdf_link}}]]"
);

// src/command/SyncArticlesCommand.ts
var import_obsidian4 = require("obsidian");
var SyncArticlesCommand = class {
  constructor(plugin) {
    this.id = "sync-articles";
    this.name = "Sync Wallabag Articles";
    this.plugin = plugin;
    this.syncedFilePath = `${this.plugin.manifest.dir}/.synced`;
  }
  async readSynced() {
    const exists = await this.plugin.app.vault.adapter.exists(this.syncedFilePath);
    if (exists) {
      return await this.plugin.app.vault.adapter.read(this.syncedFilePath).then(JSON.parse);
    } else {
      return [];
    }
  }
  async writeSynced(ids) {
    return await this.plugin.app.vault.adapter.write(this.syncedFilePath, JSON.stringify(ids));
  }
  async getUserTemplate() {
    const template = await this.plugin.app.vault.adapter.read(`${this.plugin.settings.articleTemplate}.md`);
    return new NoteTemplate(template);
  }
  getFolder(wallabagArticle) {
    if (wallabagArticle.isArchived && this.plugin.settings.archivedFolder !== "") {
      return this.plugin.settings.archivedFolder;
    } else if (!wallabagArticle.isArchived && this.plugin.settings.unreadFolder !== "") {
      return this.plugin.settings.unreadFolder;
    } else {
      return this.plugin.settings.folder;
    }
  }
  getFilename(wallabagArticle) {
    const filename = wallabagArticle.title.replaceAll(/[\\,#%&{}/*<>$"@.?]/g, " ").replaceAll(/[:|]/g, " ");
    if (this.plugin.settings.idInTitle === "true") {
      return `${filename}-${wallabagArticle.id}`;
    } else {
      return filename;
    }
  }
  async createNoteIfNotExists(filename, content) {
    const exists = await this.plugin.app.vault.adapter.exists(filename);
    if (exists) {
      new import_obsidian4.Notice(`File ${filename} already exists. Skipping..`);
    } else {
      this.plugin.app.vault.create(filename, content);
    }
  }
  async callback() {
    if (!this.plugin.authenticated) {
      new import_obsidian4.Notice("Please authenticate with Wallabag first.");
      return;
    } else if (this.plugin.settings.syncUnRead === "false" && this.plugin.settings.syncArchived === "false") {
      new import_obsidian4.Notice("Please select at least one type of article to sync.");
      return;
    }
    const previouslySynced = await this.readSynced();
    const fetchNotice = new import_obsidian4.Notice("Syncing from Wallabag..");
    const articles = await this.plugin.api.fetchArticles(
      this.plugin.settings.syncUnRead === "true" ? true : false,
      this.plugin.settings.syncArchived === "true" ? true : false
    );
    const newIds = await Promise.all(
      articles.filter((article) => !previouslySynced.contains(article.id)).map(async (article) => {
        const folder = this.getFolder(article);
        if (this.plugin.settings.downloadAsPDF !== "true") {
          const template = this.plugin.settings.articleTemplate === "" ? DefaultTemplate : await this.getUserTemplate();
          const filename = (0, import_obsidian4.normalizePath)(`${folder}/${this.getFilename(article)}.md`);
          const content = template.fill(
            article,
            this.plugin.settings.serverUrl,
            this.plugin.settings.convertHtmlToMarkdown,
            this.plugin.settings.tagFormat
          );
          await this.createNoteIfNotExists(filename, content);
        } else {
          const pdfFilename = (0, import_obsidian4.normalizePath)(`${this.plugin.settings.pdfFolder}/${this.getFilename(article)}.pdf`);
          const pdf = await this.plugin.api.exportArticle(article.id);
          await this.plugin.app.vault.adapter.writeBinary(pdfFilename, pdf);
          if (this.plugin.settings.createPDFNote) {
            const template = this.plugin.settings.articleTemplate === "" ? PDFTemplate : await this.getUserTemplate();
            const filename = (0, import_obsidian4.normalizePath)(`${folder}/${this.getFilename(article)}.md`);
            const content = template.fill(article, this.plugin.settings.serverUrl, this.plugin.settings.tagFormat, pdfFilename);
            await this.createNoteIfNotExists(filename, content);
          }
        }
        if (this.plugin.settings.archiveAfterSync === "true") {
          await this.plugin.api.archiveArticle(article.id);
        }
        return article.id;
      })
    );
    await this.writeSynced([...newIds, ...previouslySynced]);
    fetchNotice.setMessage((0, import_obsidian4.sanitizeHTMLToDom)(`Sync from Wallabag is now completed. <br> ${newIds.length} new article(s) has been synced.`));
  }
};

// src/main.ts
var import_obsidian7 = require("obsidian");

// src/settings/WallabagSettingTab.ts
var import_obsidian6 = require("obsidian");

// src/wallabag/WallabagAPI.ts
var import_obsidian5 = require("obsidian");
var WallabagAPI = class {
  constructor(token, plugin) {
    this.plugin = plugin;
    this.token = token;
  }
  static async authenticate(serverUrl, clientId, clientSecret, username, password) {
    const body = {
      grant_type: "password",
      client_id: clientId,
      client_secret: clientSecret,
      username,
      password
    };
    const requestOptions = {
      url: `${serverUrl}/oauth/v2/token`,
      method: "POST",
      body: JSON.stringify(body),
      contentType: "application/json"
    };
    const response = await (0, import_obsidian5.requestUrl)(requestOptions);
    const parsed = response.json;
    return {
      clientId,
      clientSecret,
      accessToken: parsed.access_token,
      refreshToken: parsed.refresh_token
    };
  }
  async refresh() {
    return (0, import_obsidian5.request)({
      url: `${this.plugin.settings.serverUrl}/oauth/v2/token`,
      method: "POST",
      body: `grant_type=refresh_token&refresh_token=${this.token.refreshToken}&client_id=${this.token.clientId}&client_secret=${this.token.clientSecret}`,
      contentType: "application/x-www-form-urlencoded"
    }).then((response) => {
      const parsed = JSON.parse(response);
      return {
        clientId: this.token.clientId,
        clientSecret: this.token.clientSecret,
        accessToken: parsed.access_token,
        refreshToken: parsed.refresh_token
      };
    });
  }
  convertWallabagArticle(article) {
    const getTag = (tag) => tag["slug"].startsWith("t:") ? tag["slug"].substring(2) : tag["slug"];
    return {
      id: article["id"],
      tags: article["tags"].map(getTag),
      title: article["title"],
      url: article["url"],
      content: article["content"],
      createdAt: article["created_at"],
      updatedAt: article["updated_at"],
      publishedAt: article["published_at"],
      readingTime: article["reading_time"],
      previewPicture: article["preview_picture"],
      domainName: article["domain_name"],
      annotations: article["annotations"],
      isArchived: article["is_archived"],
      isStarred: article["is_starred"],
      givenUrl: article["given_url"]
    };
  }
  convertWallabagArticlesResponse(response) {
    return {
      page: response.json["page"],
      pages: response.json["pages"],
      articles: response.json["_embedded"]["items"].map(this.convertWallabagArticle)
    };
  }
  async tokenRefreshingFetch(url, method, body) {
    return (0, import_obsidian5.requestUrl)({
      url,
      headers: {
        Authorization: `Bearer ${this.token.accessToken}`,
        "Content-Type": "application/json"
      },
      method: method ? method : "GET",
      body
    }).catch(async (reason) => {
      if (reason.status === 401) {
        console.log("Likely the token expired, refreshing it.");
        return await this.refresh().then(async (token) => {
          this.token = token;
          await this.plugin.onAuthenticated(this.token);
          return this.tokenRefreshingFetch(url);
        }).catch(async (reason2) => {
          console.log("Token refresh failed.", reason2);
          await this.plugin.onTokenRefreshFailed();
          throw new Error("");
        });
      } else {
        console.log(`Something else failed ${reason}`);
        throw new Error("");
      }
    });
  }
  getArchiveParam(syncUnReadArticles, syncArchivedArticles) {
    if (syncUnReadArticles && !syncArchivedArticles) {
      return "&archive=0";
    } else if (!syncUnReadArticles && syncArchivedArticles) {
      return "&archive=1";
    } else {
      return "";
    }
  }
  async fetchArticles(syncUnReadArticles = true, syncArchivedArticles = false, page = 1, results = []) {
    const archiveParam = this.getArchiveParam(syncUnReadArticles, syncArchivedArticles);
    const url = `${this.plugin.settings.serverUrl}/api/entries.json?page=${page}&tags=${this.plugin.settings.tag}${archiveParam}`;
    return this.tokenRefreshingFetch(url).then((value) => {
      const response = this.convertWallabagArticlesResponse(value);
      if (response.pages === response.page) {
        return [...results, ...response.articles];
      } else {
        return this.fetchArticles(syncUnReadArticles, syncArchivedArticles, page + 1, [...results, ...response.articles]);
      }
    });
  }
  async exportArticle(id, format = "pdf") {
    const url = `${this.plugin.settings.serverUrl}/api/entries/${id}/export.${format}`;
    return this.tokenRefreshingFetch(url).then((value) => {
      return value.arrayBuffer;
    });
  }
  async archiveArticle(id) {
    const url = `${this.plugin.settings.serverUrl}/api/entries/${id}`;
    return this.tokenRefreshingFetch(url, "PATCH", JSON.stringify({ archive: 1 }));
  }
};

// src/settings/WallabagSettingTab.ts
var WallabagSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin, isAuthenticated) {
    super(app, plugin);
    this.addTextSetting = (setting, el) => {
      const result = new import_obsidian6.Setting(el).setName(setting.name).setDesc(setting.desc).addText((text) => {
        text.setValue(setting.get()).onChange(async (value) => {
          setting.set(value);
        });
      });
      if (setting.class) {
        result.setClass(setting.class);
      }
    };
    this.addTextSettingHere = (setting) => {
      this.addTextSetting(setting, this.containerEl);
    };
    this.updateSetting = (key) => async (v) => {
      this.plugin.settings[key] = v;
      await this.plugin.saveSettings();
    };
    this.plugin = plugin;
    this.isAuthenticated = isAuthenticated;
  }
  display() {
    this.containerEl.empty();
    [
      {
        name: "Server URL",
        desc: "Wallabag server to connect.",
        get: () => this.plugin.settings.serverUrl,
        set: this.updateSetting("serverUrl")
      },
      {
        name: "Tag to sync",
        desc: "If set, only articles with this tag will be synced.",
        get: () => this.plugin.settings.tag,
        set: this.updateSetting("tag")
      },
      {
        name: "Wallabag article notes folder location",
        desc: "Choose the location where the synced article notes will be created.",
        get: () => this.plugin.settings.folder,
        set: this.updateSetting("folder")
      },
      {
        name: "Article note template file",
        desc: (0, import_obsidian6.sanitizeHTMLToDom)(
          'The template file that will be used for the new articles.<br> See <a href="https://github.com/huseyz/obsidian-wallabag">documentation</a> for examples.'
        ),
        get: () => this.plugin.settings.articleTemplate,
        set: this.updateSetting("articleTemplate")
      }
    ].forEach(this.addTextSettingHere);
    this.containerEl.createEl("h2", { text: "Sync Behavior" });
    new import_obsidian6.Setting(this.containerEl).setName("Sync on startup").setDesc("If enabled, articles will be synced on startup.").addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.syncOnStartup === "true").onChange(async (value) => {
        this.plugin.settings.syncOnStartup = String(value);
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian6.Setting(this.containerEl).setName("Sync unread articles").setDesc("If enabled, unread articles will be synced.").addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.syncUnRead === "true").onChange(async (value) => {
        this.plugin.settings.syncUnRead = String(value);
        await this.plugin.saveSettings();
        this.display();
      });
    });
    this.addTextSettingHere({
      name: "Wallabag unread article notes folder location",
      desc: (0, import_obsidian6.sanitizeHTMLToDom)(
        "(optional) Choose the location where the unread synced article notes will be created.<br>If not specified, the article notes folder will be used."
      ),
      get: () => this.plugin.settings.unreadFolder,
      set: this.updateSetting("unreadFolder")
    });
    new import_obsidian6.Setting(this.containerEl).setName("Sync archived articles").setDesc("If enabled, archived articles will be synced.").addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.syncArchived === "true").onChange(async (value) => {
        this.plugin.settings.syncArchived = String(value);
        await this.plugin.saveSettings();
        this.display();
      });
    });
    this.addTextSettingHere({
      name: "Wallabag archived article notes folder location",
      desc: (0, import_obsidian6.sanitizeHTMLToDom)(
        "(optional) Choose the location where the archived synced article notes will be created.<br>If not specified, the article notes folder will be used."
      ),
      get: () => this.plugin.settings.archivedFolder,
      set: this.updateSetting("archivedFolder")
    });
    new import_obsidian6.Setting(this.containerEl).setName("Archive article after sync").setDesc("If enabled the article will be archived after being synced.").addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.archiveAfterSync === "true");
      toggle.onChange(async (value) => {
        this.plugin.settings.archiveAfterSync = String(value);
        await this.plugin.saveSettings();
      });
    });
    this.containerEl.createEl("h2", { text: "Obsidian note creation" });
    new import_obsidian6.Setting(this.containerEl).setName("Convert HTML Content extracted by Wallabag to Markdown").setDesc("If enabled the content of the Wallabag article will be converted to markdown before being used for the new article.").addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.convertHtmlToMarkdown === "true");
      toggle.onChange(async (value) => {
        this.plugin.settings.convertHtmlToMarkdown = String(value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(this.containerEl).setName("Add article ID in the title").setDesc("If enabled the article ID will be added to title.").addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.idInTitle === "true");
      toggle.onChange(async (value) => {
        this.plugin.settings.idInTitle = String(value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(this.containerEl).setName("Tag format").setDesc(
      (0, import_obsidian6.sanitizeHTMLToDom)(
        "Determines how the tags will be populated in the created note. <br>CSV: Comma-separeted tags e.g. <code>tag1, tag2, tag3</code> <br>Hashtags: Space-separeted hashtags<code>#tag1 #tag2 #tag3</code> <br>"
      )
    ).addDropdown(async (dropdown) => {
      dropdown.addOption("csv", "CSV");
      dropdown.addOption("hashtag", "Hashtags");
      dropdown.setValue(this.plugin.settings.tagFormat);
      dropdown.onChange(async (value) => {
        this.plugin.settings.tagFormat = value;
        await this.plugin.saveSettings();
      });
    });
    this.containerEl.createEl("h2", { text: "Export as PDF" });
    new import_obsidian6.Setting(this.containerEl).setName("Export as PDF").setDesc("If enabled synced articles will be exported as PDFs.").addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.downloadAsPDF === "true").onChange(async (value) => {
        this.plugin.settings.downloadAsPDF = String(value);
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const pdfSettingsClass = this.plugin.settings.downloadAsPDF !== "true" ? "wallabag-setting-hidden" : "wallabag-pdf-setting";
    this.addTextSettingHere({
      name: "PDF Folder",
      desc: "The folder exported PDFs will be downloaded.",
      get: () => this.plugin.settings.pdfFolder,
      set: this.updateSetting("pdfFolder"),
      class: pdfSettingsClass
    });
    new import_obsidian6.Setting(this.containerEl).setName("Create note").setDesc(
      "If enabled a note will be created in the article note folder for each article exported as pdf. Article note template will be used if specified."
    ).setClass(pdfSettingsClass).addToggle(async (toggle) => {
      toggle.setValue(this.plugin.settings.createPDFNote === "true");
      toggle.onChange(async (value) => {
        this.plugin.settings.createPDFNote = String(value);
        await this.plugin.saveSettings();
      });
    });
    this.authenticationSettings();
  }
  authenticationSettings() {
    this.containerEl.createEl("h2", { text: "Authentication" });
    let clientId = "", clientSecret = "", username = "", password = "";
    if (this.isAuthenticated()) {
      this.containerEl.createEl("strong", { text: "You are currently authenticated, to change authentication settings, logout first." });
    }
    const authenticationClass = this.isAuthenticated() ? "wallabag-setting-hidden" : "wallabag-setting-shown";
    [
      {
        name: "Client ID",
        desc: "Wallabag client id",
        get: () => "",
        set: (v) => clientId = v,
        class: authenticationClass
      },
      {
        name: "Client Secret",
        desc: "Wallabag client secret",
        get: () => "",
        set: (v) => clientSecret = v,
        class: authenticationClass
      },
      {
        name: "Username",
        desc: "Wallabag username",
        get: () => "",
        set: (v) => username = v,
        class: authenticationClass
      },
      {
        name: "Password",
        desc: "Wallabag Password",
        get: () => "",
        set: (v) => password = v,
        class: authenticationClass
      }
    ].forEach(this.addTextSettingHere);
    new import_obsidian6.Setting(this.containerEl).addButton((button) => {
      button.setButtonText(this.isAuthenticated() ? "Logout" : "Authenticate").setClass(this.isAuthenticated() ? "mod-warning" : "mod-cta").onClick(async () => {
        if (this.isAuthenticated()) {
          await this.plugin.onLogout();
          this.display();
        } else {
          const notice = new import_obsidian6.Notice("Authenticating with Wallabag...");
          try {
            await WallabagAPI.authenticate(this.plugin.settings.serverUrl, clientId, clientSecret, username, password).then(async (token) => {
              await this.plugin.onAuthenticated(token);
              this.display();
              notice.setMessage("Authenticated with Wallabag.");
            });
          } catch (error) {
            console.log(error);
            notice.setMessage("Authentication with Wallabag failed.");
          }
        }
      });
    });
  }
};

// src/wallabag/WallabagAuth.ts
var tokenVaultPath = (plugin) => `${plugin.manifest.dir}/.__wallabag_token__`;
var storeTokenToVault = async (plugin, token) => {
  return plugin.app.vault.adapter.write(tokenVaultPath(plugin), JSON.stringify(token));
};
var loadTokenFromVault = async (plugin) => {
  const path = tokenVaultPath(plugin);
  return plugin.app.vault.adapter.exists(path).then(async (exists) => {
    if (!exists) {
      return void 0;
    } else {
      return JSON.parse(await plugin.app.vault.adapter.read(path));
    }
  });
};
var removeTokenFromVault = async (plugin) => {
  const path = tokenVaultPath(plugin);
  return plugin.app.vault.adapter.remove(path);
};

// src/settings/WallabagSettings.ts
var DEFAULT_SETTINGS = {
  serverUrl: "",
  tag: "",
  folder: "",
  downloadAsPDF: "false",
  articleTemplate: "",
  pdfFolder: "",
  createPDFNote: "false",
  convertHtmlToMarkdown: "false",
  idInTitle: "false",
  archiveAfterSync: "false",
  syncOnStartup: "false",
  syncArchived: "false",
  syncUnRead: "true",
  tagFormat: "csv",
  unreadFolder: "",
  archivedFolder: ""
};

// src/main.ts
var WallabagPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.init();
    const syncArticlesCommand = new SyncArticlesCommand(this);
    this.addSettingTab(new WallabagSettingTab(this.app, this, (_) => this.authenticated));
    this.addCommand(syncArticlesCommand);
    this.addCommand(new ClearSyncedArticlesCacheCommand(this));
    this.addCommand(new DeleteNoteAndRemoveFromSyncedCacheCommand(this));
    if (this.settings.syncOnStartup === "true") {
      syncArticlesCommand.callback();
    }
    this.addRibbonIcon("sheets-in-box", "Sync Wallabag articles", () => syncArticlesCommand.callback());
  }
  async init() {
    await this.loadSettings();
    await this.loadToken();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadToken() {
    return loadTokenFromVault(this).then((token) => {
      if (token) {
        this.api = new WallabagAPI(token, this);
        this.authenticated = true;
      } else {
        new import_obsidian7.Notice("Please authenticate with Wallabag to start syncing.");
      }
    });
  }
  async onAuthenticated(token) {
    await storeTokenToVault(this, token);
    await this.loadToken();
  }
  async onLogout() {
    await removeTokenFromVault(this);
    this.authenticated = false;
  }
  async onTokenRefreshFailed() {
    await this.onLogout();
    new import_obsidian7.Notice("Authentication refresh has failed. Please authenticate again.");
  }
};

/* nosourcemap */