/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/SnippetManagerPlugin.ts
var import_obsidian3 = require("obsidian");

// src/SnippetSuggestModal.ts
var import_obsidian = require("obsidian");
var SnippetSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, plugin, editor) {
    super(app);
    this.items = {};
    this.plugin = plugin;
    this.editor = editor;
    this.refreshSnippets();
    this.scope.register(["Mod"], "Enter", (evt) => {
      if (evt.isComposing) {
        return;
      }
      this.chooser.useSelectedItem(evt);
      return false;
    });
    this.setPlaceholder("Search snippets...");
  }
  async refreshSnippets() {
    await this.plugin.loadSnippets();
    this.items = this.plugin.snippets;
  }
  getItems() {
    return Object.keys(this.items);
  }
  getItemText(item) {
    return item;
  }
  async onChooseItem(item, evt) {
    let value = this.plugin.snippets[item];
    if (value.includes("<%")) {
      const templater = this.app.plugins.getPlugin("templater-obsidian");
      if (templater) {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          value = await templater.templater.parse_template({ target_file: activeFile, run_mode: 4 }, value);
        }
      }
    }
    navigator.clipboard.writeText(value).then(() => {
      new import_obsidian.Notice(`Copied snippet: ${item}`);
    });
    if (!this.editor) {
      return;
    }
    if (this.plugin.settings.useEnterToInsert) {
      this.insertSnippetAtCursor(value);
      return;
    }
    if (evt.metaKey || evt.ctrlKey) {
      this.insertSnippetAtCursor(value);
    }
  }
  insertSnippetAtCursor(value) {
    var _a;
    (_a = this.editor) == null ? void 0 : _a.replaceSelection(value);
  }
  onOpen() {
    super.onOpen();
    this.displayInstructions();
  }
  displayInstructions() {
    if (!this.editor) {
      this.setInstructions([
        { command: "\u21B5", purpose: "to copy to clipboard" }
      ]);
      return;
    }
    if (this.plugin.settings.useEnterToInsert) {
      this.setInstructions([
        { command: "\u21B5", purpose: "to copy and paste at cursor position" },
        { command: "\u2318 \u21B5", purpose: "to copy to clipboard" }
      ]);
      return;
    }
    this.setInstructions([
      { command: "\u21B5", purpose: "to copy to clipboard" },
      { command: "\u2318 \u21B5", purpose: "to copy and paste at cursor position" }
    ]);
  }
};

// src/SnippetManagerSettingTab.ts
var import_obsidian2 = require("obsidian");
var SnippetManagerSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Snippets locations (paths)").setDesc("Comma-separated list of file paths or folder paths (e.g. Snippets.md, Programming/)").addText((text) => text.setPlaceholder("Snippets.md, Programming/Nodejs").setValue(this.plugin.settings.snippetPath).onChange(async (value) => {
      if (value.endsWith("/")) {
        value = value.slice(0, -1);
      }
      this.plugin.settings.snippetPath = value;
      await this.plugin.saveSettings();
      this.plugin.clearSnippets();
    }));
    new import_obsidian2.Setting(containerEl).setName("Snippets tags").setDesc("Comma-separated list of tags to load snippets from (e.g. #snippet, #templates). Snippets from all files with these tags will be loaded.").addText((text) => text.setPlaceholder("#snippet, #templates").setValue(this.plugin.settings.snippetTags).onChange(async (value) => {
      this.plugin.settings.snippetTags = value;
      await this.plugin.saveSettings();
      this.plugin.clearSnippets();
    }));
    new import_obsidian2.Setting(containerEl).setName("Show full folder path as prefix").setDesc("When enabled, snippets from subdirectories or tags will include their folder path. When disabled, only the file name is used.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showFullPathAsPrefix).onChange(async (value) => {
        this.plugin.settings.showFullPathAsPrefix = value;
        await this.plugin.saveSettings();
        this.plugin.clearSnippets();
        this.plugin.loadSnippets();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Enable Alfred Support").setDesc(
      createFragment((fragment) => {
        fragment.appendText("If enabled, snippets will be saved in ");
        fragment.append(
          createEl(
            "a",
            {
              text: "Alfred",
              href: "https://www.alfredapp.com/?utm_source=Obsidian_Snippet_Manager"
            },
            (a) => {
              a.setAttr("target", "_blank");
            }
          )
        );
        fragment.appendText(" JSON format.");
        fragment.append(createEl("br"));
        fragment.appendText("Add the following file in the Alfred workflow configuration. (Just double click and copy the path)");
        fragment.append(createEl("br"));
        const fullPath = `${this.plugin.app.vault.adapter.basePath}/${this.plugin.manifest.dir}/alfred-snippets.json`;
        const pathSpan = createEl("span", { text: fullPath });
        pathSpan.style.userSelect = "text";
        fragment.append(pathSpan);
      })
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.alfredSupport).onChange(async (value) => {
        this.plugin.settings.alfredSupport = value;
        await this.plugin.saveSettings();
        if (value) {
          this.plugin.clearSnippets();
          this.plugin.loadSnippets();
        }
      })
    );
    const settingUseEnter = new import_obsidian2.Setting(containerEl).setName("Use \u21B5 to Insert Snippet?").setDesc(
      this.plugin.settings.useEnterToInsert ? "Pressing \u21B5 will insert the selected snippet." : "Pressing \u2318 \u21B5 will insert the snippet."
    ).addToggle((toggle) => toggle.setValue(this.plugin.settings.useEnterToInsert).onChange(async (value) => {
      this.plugin.settings.useEnterToInsert = value;
      settingUseEnter.setDesc(
        value ? "Pressing \u21B5 will insert the selected snippet." : "Pressing \u2318 \u21B5 will insert the snippet."
      );
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Strip Code Block Formatting").setDesc("Remove code block markdown (```) from snippet content when loading snippets.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.stripCodeBlockFormatting).onChange(async (value) => {
        this.plugin.settings.stripCodeBlockFormatting = value;
        await this.plugin.saveSettings();
        this.plugin.clearSnippets();
        this.plugin.loadSnippets();
      })
    );
  }
};

// src/SnippetManagerPlugin.ts
var DEFAULT_SETTINGS = {
  snippetPath: "Snippets.md",
  // Default to single file for backward compatibility
  snippetTags: "",
  showFullPathAsPrefix: true,
  alfredSupport: false,
  useEnterToInsert: false,
  stripCodeBlockFormatting: true
};
var SnippetManagerPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.snippets = {};
    this.snippetsByFile = {};
    // Track snippets per file
    this.lastModifiedTimes = {};
    // Track modified times for multiple files
    this.isSnippetsReloaded = false;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SnippetManagerSettingTab(this.app, this));
    this.addCommand({
      id: "open-snippet-search",
      name: "Search Snippets",
      callback: () => {
        const activeMarkdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        const editor = (activeMarkdownView == null ? void 0 : activeMarkdownView.getMode()) === "source" ? activeMarkdownView.editor : null;
        new SnippetSuggestModal(this.app, this, editor).open();
      }
    });
    this.app.workspace.onLayoutReady(() => {
      this.loadSnippets();
    });
  }
  clearSnippets() {
    this.snippets = {};
    this.snippetsByFile = {};
    this.lastModifiedTimes = {};
  }
  async loadSnippets() {
    this.isSnippetsReloaded = false;
    const rawPaths = this.settings.snippetPath ? this.settings.snippetPath.split(",").map((s) => s.trim()).filter(Boolean) : [];
    const rawTags = this.settings.snippetTags ? this.settings.snippetTags.split(",").map((s) => s.trim()).filter(Boolean).map((t) => t.startsWith("#") ? t : `#${t}`) : [];
    if (rawPaths.length === 0 && rawTags.length === 0) {
      new import_obsidian3.Notice("No snippet locations or tags provided.");
      return;
    }
    const activeFiles = [];
    const addFilePrefix = rawPaths.length > 1 || rawTags.length > 0;
    for (const rawPath of rawPaths) {
      const fileOrFolder = this.app.vault.getAbstractFileByPath(rawPath);
      if (!fileOrFolder) {
        new import_obsidian3.Notice(`Snippet location not found: ${rawPath}`);
        continue;
      }
      if (fileOrFolder instanceof import_obsidian3.TFolder) {
        const markdownFiles = this.getAllMarkdownFiles(fileOrFolder);
        const shouldAddPrefix = addFilePrefix || markdownFiles.length > 1;
        for (const file of markdownFiles) {
          activeFiles.push(file.path);
          await this.loadSnippetsFromFile(file, shouldAddPrefix, rawPath);
        }
      } else if (fileOrFolder instanceof import_obsidian3.TFile && fileOrFolder.extension === "md") {
        activeFiles.push(fileOrFolder.path);
        await this.loadSnippetsFromFile(fileOrFolder, addFilePrefix, "");
      } else {
        new import_obsidian3.Notice(`Invalid snippet location: ${rawPath}`);
      }
    }
    if (rawTags.length > 0) {
      const allFiles = this.app.vault.getMarkdownFiles();
      for (const file of allFiles) {
        const cache = this.app.metadataCache.getFileCache(file);
        if (cache) {
          const fileTags = (0, import_obsidian3.getAllTags)(cache) || [];
          for (const tag of rawTags) {
            if (fileTags.includes(tag)) {
              if (!activeFiles.includes(file.path)) {
                activeFiles.push(file.path);
                await this.loadSnippetsFromFile(file, true, "");
              }
              break;
            }
          }
        }
      }
    }
    for (const filePath in this.snippetsByFile) {
      if (!activeFiles.includes(filePath)) {
        delete this.snippetsByFile[filePath];
        delete this.lastModifiedTimes[filePath];
        this.isSnippetsReloaded = true;
      }
    }
    if (this.isSnippetsReloaded) {
      this.snippets = {};
      for (const filePath in this.snippetsByFile) {
        Object.assign(this.snippets, this.snippetsByFile[filePath]);
      }
      await this.saveSnippetsAsAlfredJson();
      this.isSnippetsReloaded = false;
    }
  }
  async loadSnippetsFromFile(file, addFilePrefix, rootPath = "") {
    const filePath = file.path;
    const fileStat = await this.app.vault.adapter.stat(filePath);
    const modifiedTime = fileStat == null ? void 0 : fileStat.mtime;
    if (modifiedTime && (!this.lastModifiedTimes[filePath] || modifiedTime > this.lastModifiedTimes[filePath])) {
      const content = await this.app.vault.cachedRead(file);
      const contentCache = this.app.metadataCache.getFileCache(file);
      let filePrefix = null;
      if (addFilePrefix) {
        if (this.settings.showFullPathAsPrefix) {
          filePrefix = this.getRelativePath(file, rootPath);
        } else {
          filePrefix = file.basename;
        }
      }
      const newSnippets = this.getSnippets(content, contentCache, filePrefix);
      this.snippetsByFile[filePath] = newSnippets;
      this.lastModifiedTimes[filePath] = modifiedTime;
      this.isSnippetsReloaded = true;
    }
  }
  getSnippets(content, contentCache, filePrefix) {
    const snippets = {};
    if (!(contentCache == null ? void 0 : contentCache.headings)) {
      return snippets;
    }
    const headings = contentCache.headings;
    const level = headings[0].level;
    for (let i = 0; i < headings.length; i++) {
      if (headings[i].level !== level) {
        new import_obsidian3.Notice(`Please follow the same heading level throughout the file`);
        return snippets;
      }
    }
    for (let i = 0; i < headings.length; i++) {
      const currentHeading = headings[i];
      let sectionContent = "";
      if (i + 1 === headings.length) {
        sectionContent = content.slice(currentHeading.position.end.offset + 1);
      } else {
        const nextHeading = headings[i + 1];
        sectionContent = content.slice(
          currentHeading.position.end.offset + 1,
          nextHeading.position.start.offset - 1
        );
      }
      if (this.settings.stripCodeBlockFormatting) {
        sectionContent = this.stripCodeBlockFormatting(sectionContent).trim();
      } else {
        sectionContent = sectionContent.trim();
      }
      const snippetKey = filePrefix && filePrefix !== "" ? `${filePrefix}: ${currentHeading.heading}` : currentHeading.heading;
      snippets[snippetKey] = sectionContent;
    }
    return snippets;
  }
  stripCodeBlockFormatting(content) {
    return content.replace(/```[\s\S]*?```/g, (match) => {
      return match.replace(/```(\w+)?\n?/, "").replace(/\n?```$/, "");
    });
  }
  // Save the snippets as a JSON file in Alfred's snippet format
  async saveSnippetsAsAlfredJson() {
    if (!this.settings.alfredSupport) {
      return;
    }
    let idCounter = 1;
    const alfredSnippets = Object.keys(this.snippets).map((key) => {
      return {
        "uid": idCounter++,
        // Unique ID for each snippet
        "title": key,
        // Snippet title
        "subtitle": this.snippets[key],
        // Snippet content
        "arg": this.snippets[key],
        // Snippet content
        "key": key
        // Set the key as the trigger keyword
      };
    });
    const jsonContent = JSON.stringify({ items: alfredSnippets }, null, 2);
    const jsonFilePath = `${this.manifest.dir}/alfred-snippets.json`;
    try {
      await this.app.vault.adapter.write(jsonFilePath, jsonContent);
    } catch (error) {
      console.error("Error saving snippets as Alfred JSON:", error);
      new import_obsidian3.Notice("Failed to save snippets as Alfred JSON");
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    if ((data == null ? void 0 : data.snippetFilePath) && !data.snippetPath) {
      data.snippetPath = data.snippetFilePath;
      delete data.snippetFilePath;
    }
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    await this.saveSettings();
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getRelativePath(file, rootPath) {
    let relativePath = file.path.slice(rootPath.length);
    if (relativePath.startsWith("/")) {
      relativePath = relativePath.slice(1);
    }
    return relativePath.replace(/\.md$/, "");
  }
  getAllMarkdownFiles(folder) {
    let markdownFiles = [];
    folder.children.forEach((child) => {
      if (child instanceof import_obsidian3.TFile && child.extension === "md") {
        markdownFiles.push(child);
      } else if (child instanceof import_obsidian3.TFolder) {
        markdownFiles = markdownFiles.concat(this.getAllMarkdownFiles(child));
      }
    });
    return markdownFiles;
  }
};

// src/main.ts
var main_default = SnippetManagerPlugin;

/* nosourcemap */