/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// node_modules/epub-cfi-resolver/index.js
var require_epub_cfi_resolver = __commonJS({
  "node_modules/epub-cfi-resolver/index.js"(exports, module2) {
    "use strict";
    if (typeof Node === "undefined") {
      ELEMENT_NODE = 1;
      TEXT_NODE = 3;
      CDATA_SECTION_NODE = 4;
    } else {
      ELEMENT_NODE = Node.ELEMENT_NODE;
      TEXT_NODE = Node.TEXT_NODE;
      CDATA_SECTION_NODE = Node.CDATA_SECTION_NODE;
    }
    var ELEMENT_NODE;
    var TEXT_NODE;
    var CDATA_SECTION_NODE;
    function cfiEscape(str) {
      return str.replace(/[\[\]\^,();]/g, "^$&");
    }
    function matchAll(str, regExp, add) {
      add = add || 0;
      var matches = [];
      var offset = 0;
      var m;
      do {
        m = str.match(regExp);
        if (!m)
          break;
        matches.push(m.index + add);
        offset += m.index + m.length;
        str = str.slice(m.index + m.length);
      } while (offset < str.length);
      return matches;
    }
    function closest(a, n) {
      var minDiff;
      var closest2;
      var i, diff;
      for (i = 0; i < a.length; i++) {
        diff = Math.abs(a[i] - n);
        if (!i || diff < minDiff) {
          diff = minDiff;
          closest2 = a[i];
        }
      }
      return closest2;
    }
    function calcSiblingCount(nodes, n, offset) {
      var count = 0;
      var lastWasElement;
      var prevOffset = 0;
      var firstNode = true;
      var i, node;
      for (i = 0; i < nodes.length; i++) {
        node = nodes[i];
        if (node.nodeType === ELEMENT_NODE) {
          if (lastWasElement || firstNode) {
            count += 2;
            firstNode = false;
          } else {
            count++;
          }
          if (n === node) {
            if (node.tagName.toLowerCase() === "img") {
              return { count, offset };
            } else {
              return { count };
            }
          }
          prevOffset = 0;
          lastWasElement = true;
        } else if (node.nodeType === TEXT_NODE || node.nodeType === CDATA_SECTION_NODE) {
          if (lastWasElement || firstNode) {
            count++;
            firstNode = false;
          }
          if (n === node) {
            return { count, offset: offset + prevOffset };
          }
          prevOffset += node.textContent.length;
          lastWasElement = false;
        } else {
          continue;
        }
      }
      throw new Error("The specified node was not found in the array of siblings");
    }
    function compareTemporal(a, b) {
      const isA = typeof a === "number";
      const isB = typeof b === "number";
      if (!isA && !isB)
        return 0;
      if (!isA && isB)
        return -1;
      if (isA && !isB)
        return 1;
      return (a || 0) - (b || 0);
    }
    function compareSpatial(a, b) {
      if (!a && !b)
        return 0;
      if (!a && b)
        return -1;
      if (a && !b)
        return 1;
      var diff = (a.y || 0) - (b.y || 0);
      if (diff)
        return diff;
      return (a.x || 0) - (b.x || 0);
    }
    var CFI2 = class {
      constructor(str, opts) {
        this.opts = Object.assign({
          // If CFI is a Simple Range, pretend it isn't
          // by parsing only the start of the range
          flattenRange: false,
          // Strip temporal, spatial, offset and textLocationAssertion
          // from places where they don't make sense
          stricter: true
        }, opts || {});
        this.cfi = str;
        const isCFI = new RegExp(/^epubcfi\((.*)\)$/);
        str = str.trim();
        var m = str.match(isCFI);
        if (!m)
          throw new Error("Not a valid CFI");
        if (m.length < 2)
          return;
        str = m[1];
        this.parts = [];
        var parsed, offset, newDoc;
        var subParts = [];
        var sawComma = 0;
        while (str.length) {
          ({ parsed, offset, newDoc } = this.parse(str));
          if (!parsed || offset === null)
            throw new Error("Parsing failed");
          if (sawComma && newDoc)
            throw new Error("CFI is a range that spans multiple documents. This is not allowed");
          subParts.push(parsed);
          if (newDoc || str.length - offset <= 0) {
            if (sawComma === 2) {
              this.to = subParts;
            } else {
              this.parts.push(subParts);
            }
            subParts = [];
          }
          str = str.slice(offset);
          if (str[0] === ",") {
            if (sawComma === 0) {
              if (subParts.length) {
                this.parts.push(subParts);
              }
              subParts = [];
            } else if (sawComma === 1) {
              if (subParts.length) {
                this.from = subParts;
              }
              subParts = [];
            }
            str = str.slice(1);
            sawComma++;
          }
        }
        if (this.from && this.from.length) {
          if (this.opts.flattenRange || !this.to || !this.to.length) {
            this.parts = this.parts.concat(this.from);
            delete this.from;
            delete this.to;
          } else {
            this.isRange = true;
          }
        }
        if (this.opts.stricter) {
          this.removeIllegalOpts();
        }
      }
      removeIllegalOpts(parts) {
        if (!parts) {
          if (this.from) {
            this.removeIllegalOpts(this.from);
            if (!this.to)
              return;
            parts = this.to;
          } else {
            parts = this.parts;
          }
        }
        var i, j, part, subpart;
        for (i = 0; i < parts.length; i++) {
          part = parts[i];
          for (j = 0; j < part.length - 1; j++) {
            subpart = part[j];
            delete subpart.temporal;
            delete subpart.spatial;
            delete subpart.offset;
            delete subpart.textLocationAssertion;
          }
        }
      }
      static generatePart(node, offset, extra) {
        var cfi = "";
        var o;
        var isSpineElement = node.parentNode.nodeName === "spine" ? true : false;
        while (node.parentNode) {
          o = calcSiblingCount(node.parentNode.childNodes, node, offset);
          if (!cfi && o.offset)
            cfi = ":" + o.offset;
          cfi = "/" + o.count + (node.id ? "[" + cfiEscape(node.id) + "]" : "") + cfi;
          node = node.parentNode;
          if (isSpineElement && node.nodeName === "package") {
            break;
          }
        }
        return cfi;
      }
      static generate(node, offset, extra) {
        var cfi;
        if (node instanceof Array) {
          var strs = [];
          for (let o of node) {
            strs.push(this.generatePart(o.node, o.offset));
          }
          cfi = strs.join("!");
        } else {
          cfi = this.generatePart(node, offset, extra);
        }
        if (extra)
          cfi += extra;
        return "epubcfi(" + cfi + ")";
      }
      static toParsed(cfi) {
        if (typeof cfi === "string")
          cif = new this(cfi);
        if (cfi.isRange) {
          return cfi.getFrom();
        } else {
          return cfi.get();
        }
      }
      // Takes two CFI paths and compares them
      static comparePath(a, b) {
        const max = Math.max(a.length, b.length);
        var i, cA, cB, diff;
        for (i = 0; i < max; i++) {
          cA = a[i];
          cB = b[i];
          if (!cA)
            return -1;
          if (!cB)
            return 1;
          diff = this.compareParts(cA, cB);
          if (diff)
            return diff;
        }
        return 0;
      }
      // Sort an array of CFI objects
      static sort(a) {
        a.sort((a2, b) => {
          return this.compare(a2, b);
        });
      }
      // Takes two CFI objects and compares them.
      static compare(a, b) {
        var oA = a.get();
        var oB = b.get();
        if (a.isRange || b.isRange) {
          if (a.isRange && b.isRange) {
            var diff = this.comparePath(oA.from, oB.from);
            if (diff)
              return diff;
            return this.comparePath(oA.to, oB.to);
          }
          if (a.isRange)
            oA = oA.from;
          if (b.isRange)
            oB = oB.from;
          return this.comparePath(oA, oB);
        } else {
          return this.comparePath(oA, oB);
        }
      }
      // Takes two parsed path parts (assuming path is split on '!') and compares them.
      static compareParts(a, b) {
        const max = Math.max(a.length, b.length);
        var i, cA, cB, diff;
        for (i = 0; i < max; i++) {
          cA = a[i];
          cB = b[i];
          if (!cA)
            return -1;
          if (!cB)
            return 1;
          diff = cA.nodeIndex - cB.nodeIndex;
          if (diff)
            return diff;
          if (cA.nodeIndex === 0) {
            return 0;
          }
          if (i < max - 1)
            continue;
          if (cA.nodeIndex % 2 === 0) {
            diff = compareTemporal(cA.temporal, cB.temporal);
            if (diff)
              return diff;
            diff = compareSpatial(cA.spatial, cB.spatial);
            if (diff)
              return diff;
          }
          diff = (cA.offset || 0) - (cB.offset || 0);
          if (diff)
            return diff;
        }
        return 0;
      }
      decodeEntities(dom, str) {
        try {
          const el = dom.createElement("textarea");
          el.innerHTML = str;
          return el.value;
        } catch (err) {
          return str;
        }
      }
      // decode HTML/XML entities and compute length
      trueLength(dom, str) {
        return this.decodeEntities(dom, str).length;
      }
      getFrom() {
        if (!this.isRange)
          throw new Error("Trying to get beginning of non-range CFI");
        if (!this.from) {
          return this.deepClone(this.parts);
        }
        const parts = this.deepClone(this.parts);
        parts[parts.length - 1] = parts[parts.length - 1].concat(this.from);
        return parts;
      }
      getTo() {
        if (!this.isRange)
          throw new Error("Trying to get end of non-range CFI");
        const parts = this.deepClone(this.parts);
        parts[parts.length - 1] = parts[parts.length - 1].concat(this.to);
        return parts;
      }
      get() {
        if (this.isRange) {
          return {
            from: this.getFrom(),
            to: this.getTo(),
            isRange: true
          };
        }
        return this.deepClone(this.parts);
      }
      parseSideBias(o, loc) {
        if (!loc)
          return;
        const m = loc.trim().match(/^(.*);s=([ba])$/);
        if (!m || m.length < 3) {
          if (typeof o.textLocationAssertion === "object") {
            o.textLocationAssertion.post = loc;
          } else {
            o.textLocationAssertion = loc;
          }
          return;
        }
        if (m[1]) {
          if (typeof o.textLocationAssertion === "object") {
            o.textLocationAssertion.post = m[1];
          } else {
            o.textLocationAssertion = m[1];
          }
        }
        if (m[2] === "a") {
          o.sideBias = "after";
        } else {
          o.sideBias = "before";
        }
      }
      parseSpatialRange(range) {
        if (!range)
          return void 0;
        const m = range.trim().match(/^([\d\.]+):([\d\.]+)$/);
        if (!m || m.length < 3)
          return void 0;
        const o = {
          x: parseInt(m[1]),
          y: parseInt(m[2])
        };
        if (typeof o.x !== "number" || typeof o.y !== "number") {
          return void 0;
        }
        return o;
      }
      parse(cfi) {
        var o = {};
        const isNumber = new RegExp(/[\d]/);
        var f;
        var state;
        var prevState;
        var cur, escape;
        var seenColon = false;
        var seenSlash = false;
        var i;
        for (i = 0; i <= cfi.length; i++) {
          if (i < cfi.length) {
            cur = cfi[i];
          } else {
            cur = "";
          }
          if (cur === "^" && !escape) {
            escape = true;
            continue;
          }
          if (state === "/") {
            if (cur.match(isNumber)) {
              if (!f) {
                f = cur;
              } else {
                f += cur;
              }
              escape = false;
              continue;
            } else {
              if (f) {
                o.nodeIndex = parseInt(f);
                f = null;
              }
              prevState = state;
              state = null;
            }
          }
          if (state === ":") {
            if (cur.match(isNumber)) {
              if (!f) {
                f = cur;
              } else {
                f += cur;
              }
              escape = false;
              continue;
            } else {
              if (f) {
                o.offset = parseInt(f);
                f = null;
              }
              prevState = state;
              state = null;
            }
          }
          if (state === "@") {
            let done = false;
            if (cur.match(isNumber) || cur === "." || cur === ":") {
              if (cur === ":") {
                if (!seenColon) {
                  seenColon = true;
                } else {
                  done = true;
                }
              }
            } else {
              done = true;
            }
            if (!done) {
              if (!f) {
                f = cur;
              } else {
                f += cur;
              }
              escape = false;
              continue;
            } else {
              prevState = state;
              state = null;
              if (f && seenColon)
                o.spatial = this.parseSpatialRange(f);
              f = null;
            }
          }
          if (state === "~") {
            if (cur.match(isNumber) || cur === ".") {
              if (!f) {
                f = cur;
              } else {
                f += cur;
              }
              escape = false;
              continue;
            } else {
              if (f) {
                o.temporal = parseFloat(f);
              }
              prevState = state;
              state = null;
              f = null;
            }
          }
          if (!state) {
            if (cur === "!") {
              i++;
              state = cur;
              break;
            }
            if (cur === ",") {
              break;
            }
            if (cur === "/") {
              if (seenSlash) {
                break;
              } else {
                seenSlash = true;
                prevState = state;
                state = cur;
                escape = false;
                continue;
              }
            }
            if (cur === ":" || cur === "~" || cur === "@") {
              if (this.opts.stricter) {
                if (cur === ":" && (typeof o.temporal !== "undefined" || typeof o.spatial !== "undefined")) {
                  break;
                }
                if ((cur === "~" || cur === "@") && typeof o.offset !== "undefined") {
                  break;
                }
              }
              prevState = state;
              state = cur;
              escape = false;
              seenColon = false;
              continue;
            }
            if (cur === "[" && !escape && prevState === ":") {
              prevState = state;
              state = "[";
              escape = false;
              continue;
            }
            if (cur === "[" && !escape && prevState === "/") {
              prevState = state;
              state = "nodeID";
              escape = false;
              continue;
            }
          }
          if (state === "[") {
            if (cur === "]" && !escape) {
              prevState = state;
              state = null;
              this.parseSideBias(o, f);
              f = null;
            } else if (cur === "," && !escape) {
              o.textLocationAssertion = {};
              if (f) {
                o.textLocationAssertion.pre = f;
              }
              f = null;
            } else {
              if (!f) {
                f = cur;
              } else {
                f += cur;
              }
            }
            escape = false;
            continue;
          }
          if (state === "nodeID") {
            if (cur === "]" && !escape) {
              prevState = state;
              state = null;
              o.nodeID = f;
              f = null;
            } else {
              if (!f) {
                f = cur;
              } else {
                f += cur;
              }
            }
            escape = false;
            continue;
          }
          escape = false;
        }
        if (!o.nodeIndex && o.nodeIndex !== 0)
          throw new Error("Missing child node index in CFI");
        return { parsed: o, offset: i, newDoc: state === "!" };
      }
      // The CFI counts child nodes differently from the DOM
      // Retrive the child of parentNode at the specified index
      // according to the CFI standard way of counting
      getChildNodeByCFIIndex(dom, parentNode, index, offset) {
        const children = parentNode.childNodes;
        if (!children.length)
          return { node: parentNode, offset: 0 };
        if (index <= 0) {
          return { node: children[0], relativeToNode: "before", offset: 0 };
        }
        var cfiCount = 0;
        var lastChild;
        var i, child;
        for (i = 0; i < children.length; i++) {
          child = children[i];
          switch (child.nodeType) {
            case ELEMENT_NODE:
              if (cfiCount % 2 === 0) {
                cfiCount += 2;
                if (cfiCount >= index) {
                  if (child.tagName.toLowerCase() === "img" && offset) {
                    return { node: child, offset };
                  }
                  return { node: child, offset: 0 };
                }
              } else {
                cfiCount += 1;
                if (cfiCount === index) {
                  if (child.tagName.toLowerCase() === "img" && offset) {
                    return { node: child, offset };
                  }
                  return { node: child, offset: 0 };
                } else if (cfiCount > index) {
                  if (!lastChild) {
                    return { node: parentNode, offset: 0 };
                  }
                  return { node: lastChild, offset: this.trueLength(dom, lastChild.textContent) };
                }
              }
              lastChild = child;
              break;
            case TEXT_NODE:
            case CDATA_SECTION_NODE:
              if (cfiCount === 0 || cfiCount % 2 === 0) {
                cfiCount += 1;
              } else {
              }
              if (cfiCount === index) {
                let trueLength = this.trueLength(dom, child.textContent);
                if (offset >= trueLength) {
                  offset -= trueLength;
                } else {
                  return { node: child, offset };
                }
              }
              lastChild = child;
              break;
            default:
              continue;
          }
        }
        if (index > cfiCount) {
          var o = { relativeToNode: "after", offset: 0 };
          if (!lastChild) {
            o.node = parentNode;
          } else {
            o.node = lastChild;
          }
          if (this.isTextNode(o.node)) {
            o.offset = this.trueLength(dom, o.node.textContent.length);
          }
          return o;
        }
      }
      isTextNode(node) {
        if (!node)
          return false;
        if (node.nodeType === TEXT_NODE || node.nodeType === CDATA_SECTION_NODE) {
          return true;
        }
        return false;
      }
      // Use a Text Location Assertion to correct and offset
      correctOffset(dom, node, offset, assertion) {
        var curNode = node;
        if (typeof assertion === "string") {
          var matchStr = this.decodeEntities(dom, assertion);
        } else {
          assertion.pre = this.decodeEntities(dom, assertion.pre);
          assertion.post = this.decodeEntities(dom, assertion.post);
          var matchStr = assertion.pre + "." + assertion.post;
        }
        if (!this.isTextNode(node)) {
          return { node, offset: 0 };
        }
        while (this.isTextNode(curNode.previousSibling)) {
          curNode = curNode.previousSibling;
        }
        const startNode = curNode;
        var str;
        const nodeLengths = [];
        var txt = "";
        var i = 0;
        while (this.isTextNode(curNode)) {
          str = this.decodeEntities(dom, curNode.textContent);
          nodeLengths[i] = str.length;
          txt += str;
          if (!curNode.nextSibling)
            break;
          curNode = curNode.nextSibling;
          i++;
        }
        const matchOffset = assertion.pre ? assertion.pre.length : 0;
        const m = matchAll(txt, new RegExp(matchStr), matchOffset);
        if (!m.length)
          return { node, offset };
        var newOffset = closest(m, offset);
        if (curNode === node && newOffset === offset) {
          return { node, offset };
        }
        i = 0;
        curNode = startNode;
        while (newOffset >= nodeLengths[i]) {
          newOffset -= nodeLengths[i];
          if (newOffset < 0)
            return { node, offset };
          if (!curNode.nextSibling || i + 1 >= nodeOffsets.length)
            return { node, offset };
          i++;
          curNode = curNode.nextSibling;
        }
        return { node: curNode, offset: newOffset };
      }
      resolveNode(index, subparts, dom, opts) {
        opts = Object.assign({}, opts || {});
        if (!dom)
          throw new Error("Missing DOM argument");
        var startNode;
        if (index === 0) {
          startNode = dom.querySelector("package");
        }
        if (!startNode) {
          for (let n of dom.childNodes) {
            if (n.nodeType === ELEMENT_NODE) {
              startNode = n;
              break;
            }
          }
        }
        if (!startNode)
          throw new Error("Document incompatible with CFIs");
        var node = startNode;
        var startFrom = 0;
        var i, subpart;
        for (i = subparts.length - 1; i >= 0; i--) {
          subpart = subparts[i];
          if (!opts.ignoreIDs && subpart.nodeID && (node = dom.getElementById(subpart.nodeID))) {
            startFrom = i + 1;
            break;
          }
        }
        if (!node) {
          node = startNode;
        }
        var o = { node, offset: 0 };
        var nodeIndex;
        for (i = startFrom; i < subparts.length; i++) {
          subpart = subparts[i];
          o = this.getChildNodeByCFIIndex(dom, o.node, subpart.nodeIndex, subpart.offset);
          if (subpart.textLocationAssertion) {
            o = this.correctOffset(dom, o.node, subpart.offset, subpart.textLocationAssertion);
          }
        }
        return o;
      }
      // Each part of a CFI (as separated by '!')
      // references a separate HTML/XHTML/XML document.
      // This function takes an index specifying the part
      // of the CFI and the appropriate Document or XMLDocument
      // that is referenced by the specified part of the CFI
      // and returns the URI for the document referenced by
      // the next part of the CFI
      // If the opt `ignoreIDs` is true then IDs
      // will not be used while resolving
      resolveURI(index, dom, opts) {
        opts = opts || {};
        if (index < 0 || index > this.parts.length - 2) {
          throw new Error("index is out of bounds");
        }
        const subparts = this.parts[index];
        if (!subparts)
          throw new Error("Missing CFI part for index: " + index);
        var o = this.resolveNode(index, subparts, dom, opts);
        var node = o.node;
        const tagName = node.tagName.toLowerCase();
        if (tagName === "itemref" && node.parentNode.tagName.toLowerCase() === "spine") {
          const idref = node.getAttribute("idref");
          if (!idref)
            throw new Error("Referenced node had not 'idref' attribute");
          node = dom.getElementById(idref);
          if (!node)
            throw new Error("Specified node is missing from manifest");
          const href = node.getAttribute("href");
          if (!href)
            throw new Error("Manifest item is missing href attribute");
          return href;
        }
        if (tagName === "iframe" || tagName === "embed") {
          const src = node.getAttribute("src");
          if (!src)
            throw new Error(tagName + " element is missing 'src' attribute");
          return src;
        }
        if (tagName === "object") {
          const data = node.getAttribute("data");
          if (!data)
            throw new Error(tagName + " element is missing 'data' attribute");
          return data;
        }
        if (tagName === "image" || tagName === "use") {
          const href = node.getAttribute("xlink:href");
          if (!href)
            throw new Error(tagName + " element is missing 'xlink:href' attribute");
          return href;
        }
        throw new Error("No URI found");
      }
      deepClone(o) {
        return JSON.parse(JSON.stringify(o));
      }
      resolveLocation(dom, parts) {
        const index = parts.length - 1;
        const subparts = parts[index];
        if (!subparts)
          throw new Error("Missing CFI part for index: " + index);
        var o = this.resolveNode(index, subparts, dom);
        var lastpart = this.deepClone(subparts[subparts.length - 1]);
        delete lastpart.nodeIndex;
        if (!lastpart.offset)
          delete o.offset;
        Object.assign(lastpart, o);
        return lastpart;
      }
      // Takes the Document or XMLDocument for the final
      // document referenced by the CFI
      // and returns the node and offset into that node
      resolveLast(dom, opts) {
        opts = Object.assign({
          range: false
        }, opts || {});
        if (!this.isRange) {
          return this.resolveLocation(dom, this.parts);
        }
        if (opts.range) {
          const range = dom.createRange();
          const from = this.getFrom();
          if (from.relativeToNode === "before") {
            range.setStartBefore(from.node, from.offset);
          } else if (from.relativeToNode === "after") {
            range.setStartAfter(from.node, from.offset);
          } else {
            range.setStart(from.node, from.offset);
          }
          const to = this.getTo();
          if (to.relativeToNode === "before") {
            range.setEndBefore(to.node, to.offset);
          } else if (to.relativeToNode === "after") {
            range.setEndAfter(to.node, to.offset);
          } else {
            range.setEnd(to.node, to.offset);
          }
          return range;
        }
        return {
          from: this.resolveLocation(dom, this.getFrom()),
          to: this.resolveLocation(dom, this.getTo()),
          isRange: true
        };
      }
      async fetchAndParse(uri) {
        return new Promise((resolv, reject) => {
          const xhr = new XMLHttpRequest();
          xhr.open("GET", uri);
          xhr.responseType = "document";
          xhr.onload = function() {
            if (xhr.readyState === xhr.DONE) {
              if (xhr.status < 200 || xhr.status >= 300) {
                reject(new Error("Failed to get: " + uri));
                return;
              }
              resolv(xhr.responseXML);
            }
          };
          xhr.onerror = function() {
            reject(new Error("Failed to get: " + uri));
          };
          xhr.send();
        });
      }
      async resolve(uriOrDoc, fetchCB, opts) {
        if (typeof fetchCB !== "function") {
          opts = fetchCB;
          fetchCB = null;
        }
        if (!fetchCB) {
          if (typeof XMLHttpRequest === "undefined") {
            throw new Error("XMLHttpRequest not available. You must supply a function as the second argument.");
          }
          fetchCB = this.fetchAndParse;
        }
        var uri, doc;
        if (typeof uriOrDoc === "string") {
          uri = uriOrDoc;
        } else {
          doc = uriOrDoc;
        }
        var i, part, uri;
        for (i = 0; i < this.parts.length - 1; i++) {
          if (uri)
            doc = await fetchCB(uri);
          uri = this.resolveURI(i, doc, opts);
        }
        if (uri)
          doc = await fetchCB(uri);
        return this.resolveLast(doc, opts);
      }
    };
    module2.exports = CFI2;
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PocketbookCloudHighlightsImporterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/import.ts
var import_obsidian2 = require("obsidian");

// src/apiclient.ts
var import_obsidian = require("obsidian");
var PocketbookCloudApiClient = class {
  constructor(login_client) {
    this.login_client = login_client;
  }
  async getBooks() {
    const access_token = await this.login_client.getAccessToken();
    const books = await (0, import_obsidian.requestUrl)({
      url: "https://cloud.pocketbook.digital/api/v1.0/books?limit=500",
      //TODO: pagination!
      method: "GET",
      headers: {
        Authorization: `Bearer ${access_token}`,
        "Cache-Control": "no-cache"
      }
    }).then((response) => response.json.items);
    return books;
  }
  async getHighlightIdsForBook(fast_hash) {
    const access_token = await this.login_client.getAccessToken();
    const response = await (0, import_obsidian.requestUrl)({
      url: `https://cloud.pocketbook.digital/api/v1.0/notes?` + new URLSearchParams({ fast_hash }),
      //TODO: pagination!? unsure, never had that many notes.
      method: "GET",
      headers: {
        Authorization: `Bearer ${access_token}`,
        "Cache-Control": "no-cache"
      }
    });
    if (!response.status || response.status < 200 || response.status >= 300) {
      switch (response.status) {
        case 401:
          throw new Error("Unauthorized: Invalid or expired access token");
        case 403:
          throw new Error("Forbidden: Access denied to the requested resource");
        case 404:
          throw new Error("Not found: Book or highlights not found");
        case 429:
          throw new Error("Rate limit exceeded: Too many requests");
        case 500:
          throw new Error("Server error: Internal server error occurred");
        case 503:
          throw new Error("Service unavailable: Server is temporarily unavailable");
        default:
          throw new Error(`HTTP error ${response.status}: Request failed`);
      }
    }
    let highlights;
    try {
      highlights = response.json;
      if (!Array.isArray(highlights)) {
        throw new Error("Invalid response format: Expected an array of highlights");
      }
    } catch (error) {
      if (error instanceof SyntaxError) {
        throw new Error("Invalid JSON response from server");
      }
      throw error;
    }
    return highlights;
  }
  async getHighlight(uuid, fast_hash) {
    const access_token = await this.login_client.getAccessToken();
    const highlight = await (0, import_obsidian.requestUrl)({
      url: `https://cloud.pocketbook.digital/api/v1.0/notes/${uuid}?` + new URLSearchParams({ fast_hash }),
      method: "GET",
      headers: {
        Authorization: `Bearer ${access_token}`,
        "Cache-Control": "no-cache"
      }
    }).then((response) => response.json);
    return highlight;
  }
  //for some reason, the access tokens in the provided link seem to be invalid
  async getBookCover(book) {
    const access_token = await this.login_client.getAccessToken();
    const cover = await (0, import_obsidian.requestUrl)({
      url: book.metadata.cover[0].path,
      method: "GET",
      headers: {
        Authorization: `Bearer ${access_token}`,
        "Cache-Control": "no-cache"
      }
    }).then((response) => response.arrayBuffer);
    return cover;
  }
};
var PocketbookCloudLoginClient = class {
  constructor(plugin, username, password, shop_name, access_token, refresh_token, access_token_valid_until) {
    this.plugin = plugin;
    this.username = username;
    this.password = password;
    this.shop_name = shop_name;
    this.access_token = access_token;
    this.refresh_token = refresh_token;
    this.access_token_valid_until = access_token_valid_until;
    // these values are taken from a login session of the official pocketbook cloud app
    // apparently they're not using PKCE; I take this as public knowledge and simply check it in.
    this.client_id = "qNAx1RDb";
    this.client_secret = "K3YYSjCgDJNoWKdGVOyO1mrROp3MMZqqRNXNXTmh";
  }
  async login() {
    if (!this.username || this.username.trim() === "") {
      new import_obsidian.Notice("\u274C Error: Username is required and cannot be empty");
    }
    if (!this.client_id || this.client_id.trim() === "") {
      new import_obsidian.Notice("\u274C Error: Client ID is required and cannot be empty");
    }
    if (!this.client_secret || this.client_secret.trim() === "") {
      new import_obsidian.Notice("\u274C Error: Client secret is required and cannot be empty");
    }
    const shops = await fetch(
      "https://cloud.pocketbook.digital/api/v1.0/auth/login?" + new URLSearchParams({
        username: this.username,
        client_id: this.client_id,
        client_secret: this.client_secret
      })
    ).then((response) => response.json()).then((data) => {
      return data;
    }).then((data) => data.providers.filter((item) => item.name.includes(this.shop_name)));
    const login_responses = await Promise.all(
      shops.map(async (shop) => {
        let result;
        try {
          if (this.refresh_token) {
            result = await (0, import_obsidian.requestUrl)({
              url: "https://cloud.pocketbook.digital/api/v1.0/auth/renew-token",
              method: "POST",
              contentType: "application/x-www-form-urlencoded",
              headers: {
                Authorization: `Bearer ${this.access_token}`
              },
              body: new URLSearchParams({
                grant_type: "refresh_token",
                refresh_token: this.refresh_token
              }).toString()
            }).then((response) => response.json);
          } else if (this.password) {
            result = await (0, import_obsidian.requestUrl)({
              url: `https://cloud.pocketbook.digital/api/v1.0/auth/login/${shop.alias}`,
              method: "POST",
              contentType: "application/x-www-form-urlencoded",
              body: new URLSearchParams({
                shop_id: shop.shop_id,
                username: this.username,
                password: this.password,
                client_id: this.client_id,
                client_secret: this.client_secret,
                grant_type: "password",
                language: "en"
              }).toString()
            }).then((response) => response.json);
          }
        } catch (error) {
          result = null;
        }
        return { shop, result };
      })
    );
    const login_response = login_responses.filter((response) => response.result).first();
    if (!login_response) {
      throw new Error("Could not log in to Pocketbook Cloud - check if username / password are correct.");
    }
    this.access_token = login_response.result.access_token;
    this.refresh_token = login_response.result.refresh_token;
    this.access_token_valid_until = new Date(Date.now() + login_response.result.expires_in * 1e3 - 5 * 60 * 1e3);
    this.plugin.settings.access_token = this.access_token;
    this.plugin.settings.refresh_token = this.refresh_token;
    this.plugin.settings.access_token_valid_until = this.access_token_valid_until;
    this.plugin.settings.shop_name = login_response.shop.name;
    await this.plugin.saveSettings();
  }
  async getAccessToken() {
    if (!this.access_token || this.access_token_valid_until < new Date()) {
      await this.login();
    }
    return this.access_token;
  }
  async getRefreshToken() {
    if (!this.refresh_token) {
      await this.login();
    }
    return this.refresh_token;
  }
  getAccessTokenValidUntil() {
    return this.access_token_valid_until;
  }
};

// src/import.ts
var CFI = require_epub_cfi_resolver();
var PocketbookCloudHighlightsImporter = class {
  constructor(app, plugin, settings) {
    this.app = app;
    this.plugin = plugin;
    this.settings = settings;
    this.login_client = new PocketbookCloudLoginClient(
      plugin,
      settings.username,
      null,
      settings.shop_name,
      settings.access_token,
      settings.refresh_token,
      settings.access_token_valid_until
    );
    this.api_client = new PocketbookCloudApiClient(this.login_client);
  }
  async importHighlights() {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q;
    new import_obsidian2.Notice("Importing highlights...");
    const books = await this.api_client.getBooks();
    for (const book of books) {
      new import_obsidian2.Notice(`Importing ${book.title}`);
      const highlightIds = await this.api_client.getHighlightIdsForBook(book.fast_hash);
      const highlights = await Promise.all(highlightIds.map((highlightInfo) => this.api_client.getHighlight(highlightInfo.uuid, book.fast_hash)));
      if (highlights.length > 0) {
        const sanitized_book_title = book.title.replace(/[\.#%&{}\\<>*\?/$!'":@+`|=]/g, "");
        const folder = `${this.settings.import_folder}/${sanitized_book_title}`;
        this.createFolder(folder);
        this.createFolder(`${folder}/highlights`);
        const metadata_filename = `${folder}/metadata.md`;
        const book_yaml_frontmatter = {
          title: book.title,
          authors: book.metadata.authors,
          isbn: book.metadata.isbn,
          year: book.metadata.year,
          id: book.id,
          fast_hash: book.fast_hash,
          collections: ((_a = book.collections) != null ? _a : "").split(","),
          uploaded_at: book.created_at,
          read_status: book.read_status,
          type: "book",
          plugin: "pocketbook-cloud-highlights-importer"
        };
        const content = (
          // not using multiline strings because they mess up indentation
          "---\n" + (0, import_obsidian2.stringifyYaml)(book_yaml_frontmatter) + `---

\`\`\`dataviewjs
dv.header(2, dv.current().title)
const queryResult = await dv.query(\`
  TABLE WITHOUT ID text, note
  FROM "${folder}/highlights"
  WHERE book_id="${book.id}" AND type = "highlight" and plugin = "pocketbook-cloud-highlights-importer"
  SORT sort_order
\`);

const result = queryResult.value.values.map(line => "> [!quote]\\n> " + line[0].replace(/\\n/g, "\\n> ") + (line[1] ? "\\n\\n> [!note]\\n> " + line[1].replace(/\\n/g, "\\n> ") : ""))

dv.list(result)
\`\`\`
`
        );
        await this.writeFile(metadata_filename, content);
        try {
          highlights.sort((a, b) => CFI.compare(this.cfi(a.quotation.begin), this.cfi(b.quotation.begin)));
        } catch (e) {
          highlights.sort((a, b) => {
            var _a2, _b2;
            return +((_a2 = a.quotation) == null ? void 0 : _a2.updated) - +((_b2 = b.quotation) == null ? void 0 : _b2.updated);
          });
        }
        let i = 0;
        for (const highlight of highlights) {
          i++;
          const file_name = `${folder}/highlights/${highlight.uuid}.md`;
          const highlight_yaml_frontmatter = {
            id: highlight.uuid,
            book_id: book.id,
            book_fast_hash: book.fast_hash,
            color: (_c = (_b = highlight.color) == null ? void 0 : _b.value) != null ? _c : "unknown",
            note: (_e = (_d = highlight.note) == null ? void 0 : _d.text) != null ? _e : "",
            text: (_g = (_f = highlight.quotation) == null ? void 0 : _f.text) != null ? _g : "",
            pointer: {
              begin: (_i = (_h = highlight.quotation) == null ? void 0 : _h.begin) != null ? _i : "",
              end: (_k = (_j = highlight.quotation) == null ? void 0 : _j.end) != null ? _k : ""
            },
            updated: (_l = highlight.quotation) == null ? void 0 : _l.updated,
            type: "highlight",
            plugin: "pocketbook-cloud-highlights-importer",
            sort_order: i
          };
          const content2 = (
            // not using multiline strings because they mess up indentation
            "---\n" + (0, import_obsidian2.stringifyYaml)(highlight_yaml_frontmatter) + `---

> [!quote]
> ${((_n = (_m = highlight.quotation) == null ? void 0 : _m.text) != null ? _n : "").replace(/\n/g, "\n> ")}

` + //
            (((_o = highlight.note) == null ? void 0 : _o.text) ? `> [!note]
> ${((_q = (_p = highlight.note) == null ? void 0 : _p.text) != null ? _q : "").replace(/\n/g, "\n> ")}
` : "")
          );
          await this.writeFile(file_name, content2);
        }
      }
    }
    new import_obsidian2.Notice("Import done");
  }
  async createFolder(folder) {
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
  }
  async writeFile(file_name, content) {
    const file = this.app.vault.getAbstractFileByPath(file_name);
    if (!file) {
      await this.app.vault.create(file_name, content);
    } else if (file instanceof import_obsidian2.TFile) {
      await this.app.vault.modify(file, content);
    } else {
      throw new Error(`File ${file_name} is not a TFile, can only write to files.`);
    }
  }
  async writeFileBinary(file_name, content) {
    const file = this.app.vault.getAbstractFileByPath(file_name);
    if (!file) {
      await this.app.vault.createBinary(file_name, content);
    } else if (file instanceof import_obsidian2.TFile) {
      await this.app.vault.modifyBinary(file, content);
    } else {
      throw new Error(`File ${file_name} is not a TFile, can only write to files.`);
    }
  }
  cfi(cfi) {
    return new CFI(cfi.substring(cfi.indexOf("epubcfi")));
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  username: "",
  shop_name: "",
  access_token: "",
  access_token_valid_until: new Date(),
  refresh_token: "",
  import_folder: ""
};
var PocketbookCloudHighlightsImporterSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Settings for Pocketbook Cloud Highlights Importer Plugin" });
    new import_obsidian3.Setting(containerEl).setName("Username").setDesc("The mail address you log in to the pocketbook cloud with").addText(
      (text) => text.setPlaceholder("crocodile@example.com").setValue(this.plugin.settings.username).onChange(async (value) => {
        this.plugin.settings.username = value;
        await this.plugin.saveSettings();
      })
    );
    let shop_name_text_field;
    new import_obsidian3.Setting(containerEl).setName("Credentials").setDesc("Use this to log in").addButton(
      (button) => button.setButtonText("Log in").onClick(async () => {
        new PocketbookCloudHighlightsImporterPasswordInput(this.app, async (password) => {
          const api_client = new PocketbookCloudLoginClient(
            this.plugin,
            this.plugin.settings.username,
            password,
            this.plugin.settings.shop_name,
            null,
            null,
            new Date()
          );
          try {
            await api_client.login();
          } catch (error) {
            new import_obsidian3.Notice(`\u274C Error logging in: ${error.message}`);
            return;
          }
          this.plugin.settings.access_token = await api_client.getAccessToken();
          this.plugin.settings.access_token_valid_until = api_client.getAccessTokenValidUntil();
          this.plugin.settings.refresh_token = await api_client.getRefreshToken();
          await this.plugin.saveSettings();
          shop_name_text_field.setValue(this.plugin.settings.shop_name);
          new import_obsidian3.Notice("Logged in successfully");
        }).open();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Shop name").setDesc(
      "The name of the shop you are logging in to. Will be auto-filled on login - only change if that does not work well and you know what you are doing."
    ).addText((text) => {
      shop_name_text_field = text;
      text.setPlaceholder("").setValue(this.plugin.settings.shop_name).onChange(async (value) => {
        this.plugin.settings.shop_name = value;
        await this.plugin.saveSettings();
      });
      return text;
    });
    new import_obsidian3.Setting(containerEl).setName("Import Folder").setDesc("The folder the plugin will write to. The folder should be empty, do not store other data here.").addText(
      (text) => text.setPlaceholder("Enter your folder path from vault root").setValue(this.plugin.settings.import_folder).onChange(async (value) => {
        this.plugin.settings.import_folder = value.replace(/^\//, "");
        await this.plugin.saveSettings();
      })
    );
  }
};
var PocketbookCloudHighlightsImporterPasswordInput = class extends import_obsidian3.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter your password (password will not be saved)." });
    new import_obsidian3.Setting(contentEl).setName("Password").addText(
      (text) => text.onChange((value) => {
        this.password = value;
      })
    );
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Submit").setCta().onClick(() => {
        this.close();
        this.onSubmit(this.password);
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var PocketbookCloudHighlightsImporterPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.importer = new PocketbookCloudHighlightsImporter(this.app, this, this.settings);
    this.addCommand({
      id: "perform-import",
      name: "Import highlights & notes",
      callback: () => {
        this.importer.importHighlights();
      }
    });
    this.addSettingTab(new PocketbookCloudHighlightsImporterSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.access_token_valid_until = new Date(this.settings.access_token_valid_until);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.importer = new PocketbookCloudHighlightsImporter(this.app, this, this.settings);
  }
};

/* nosourcemap */